#!/bin/sh
# gl-switch-podkop installer
# https://github.com/xxcay/gl-switch-podkop
#
# Hooks the physical mode switch found on many GL.iNet routers to podkop's
# "Fully Routed IPs" setting, so flipping the switch instantly routes all
# traffic for one or more local devices through your VPN/tunnel, and flipping
# it back returns them to podkop's normal (partial) routing rules.
#
# Tested on: GL.iNet Beryl AX (GL-MT3000), OpenWrt 24.10.
# Should also work on other GL.iNet routers that ship the gl-sdk4-switch-button
# package and expose /etc/gl-switch.d/ hook scripts.

set -e

SCRIPT_PATH="/etc/gl-switch.d/podkop.sh"

if ! command -v uci >/dev/null 2>&1; then
    echo "This must be run on the router itself (uci not found)." >&2
    exit 1
fi

if [ ! -d /etc/gl-switch.d ]; then
    echo "/etc/gl-switch.d not found — this router doesn't appear to have the" >&2
    echo "GL.iNet gl-switch mechanism this script relies on." >&2
    exit 1
fi

if [ ! -f /etc/config/podkop ]; then
    echo "podkop is not installed (/etc/config/podkop not found)." >&2
    echo "Install podkop first: https://github.com/itdoginfo/podkop" >&2
    exit 1
fi

echo "=== gl-switch-podkop installer ==="
echo
echo "Enter the local IP address(es) of the device(s) you want to FULLY route"
echo "through your VPN/tunnel when the switch is flipped ON."
echo
echo "IMPORTANT: use the IP of the device you're setting this up for right now"
echo "(e.g. your own computer or phone) — NOT the router's own address."
echo "For several devices, separate the IPs with spaces."
echo
printf "IP address(es): "
read -r TARGET_IPS

if [ -z "$TARGET_IPS" ]; then
    echo "No IP entered, aborting." >&2
    exit 1
fi

cat > "$SCRIPT_PATH" << EOF
#!/bin/sh
# Generated by gl-switch-podkop installer — https://github.com/xxcay/gl-switch-podkop
# Re-run install.sh to change the IP list, or edit TARGET_IPS below by hand.

TARGET_IPS="$TARGET_IPS"

[ "\$1" = "on" ] && MODE="add" || MODE="del"

. /lib/functions.sh

toggle_section() {
    local section="\$1"
    local ip
    for ip in \$TARGET_IPS; do
        uci -q del_list podkop."\${section}".fully_routed_ips="\$ip"
        [ "\$MODE" = "add" ] && uci add_list podkop."\${section}".fully_routed_ips="\$ip"
    done
}

config_load podkop
config_foreach toggle_section section

uci commit podkop
/etc/init.d/podkop reload

logger -t gl-switch-podkop "podkop fully_routed_ips: \${MODE} [\$TARGET_IPS] (arg=\$1)"

exit 0
EOF

chmod 755 "$SCRIPT_PATH"

uci set switch-button.@main[0].func='podkop'
uci commit switch-button

echo
echo "Done."
echo
echo "Test it:"
echo "  logread -f"
echo "and flip the switch. You should see a 'gl-switch-podkop' log line, and:"
echo "  uci show podkop | grep fully_routed_ips"
echo "should show/hide your IP(s) depending on the switch position."
echo
echo "If ON and OFF turn out reversed for your physical switch direction,"
echo "edit $SCRIPT_PATH and swap the 'on'/'off' branch in the second line."
